name: New Feature
description: Request or define a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the new feature
      placeholder: What should be added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem
      description: Why is this feature needed?
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this be implemented?
      placeholder: High-level approach
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Feature works as expected
        - label: Tests added or updated
        - label: Documentation updated (if needed)
