enum LogAction {
  // Appointment Actions
  CREATE_APPOINTMENT = "CREATE_APPOINTMENT",
  CREATE_APPOINTMENT_FAILED = "CREATE_APPOINTMENT_FAILED",
  UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT",
  UPDATE_APPOINTMENT_FAILED = "UPDATE_APPOINTMENT_FAILED",
  FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS",
  FETCH_APPOINTMENTS_FAILED = "FETCH_APPOINTMENTS_FAILED",

  // Patient Actions
  CREATE_PATIENT = "CREATE_PATIENT",
  CREATE_PATIENT_FAILED = "CREATE_PATIENT_FAILED",
  UPDATE_PATIENT = "UPDATE_PATIENT",
  UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED",
  FETCH_PATIENTS = "FETCH_PATIENTS",
  FETCH_PATIENTS_FAILED = "FETCH_PATIENTS_FAILED",

  // Doctor Actions
  UPDATE_DOCTOR = "UPDATE_DOCTOR",
  UPDATE_DOCTOR_FAILED = "UPDATE_DOCTOR_FAILED",
  FETCH_DOCTORS = "FETCH_DOCTORS",
  FETCH_DOCTORS_FAILED = "FETCH_DOCTORS_FAILED",

  // Treatment Actions
  CREATE_TREATMENT = "CREATE_TREATMENT",
  CREATE_TREATMENT_FAILED = "CREATE_TREATMENT_FAILED",
  FETCH_TREATMENTS = "FETCH_TREATMENTS",
  FETCH_TREATMENTS_FAILED = "FETCH_TREATMENTS_FAILED",

  // Document Actions
  UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
  UPLOAD_DOCUMENT_FAILED = "UPLOAD_DOCUMENT_FAILED",
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  DELETE_DOCUMENT_FAILED = "DELETE_DOCUMENT_FAILED",
  FETCH_DOCUMENTS = "FETCH_DOCUMENTS",
  FETCH_DOCUMENTS_FAILED = "FETCH_DOCUMENTS_FAILED",

  // Secretary Actions
  FETCH_SECRETARIES = "FETCH_SECRETARIES",
  FETCH_SECRETARIES_FAILED = "FETCH_SECRETARIES_FAILED",

  // User Actions
  FETCH_USERS = "FETCH_USERS",
  FETCH_USERS_FAILED = "FETCH_USERS_FAILED",

  // Auth Actions
  SIGN_IN = "SIGN_IN",
  SIGN_IN_FAILED = "SIGN_IN_FAILED",
  SIGN_UP = "SIGN_UP",
  SIGN_UP_FAILED = "SIGN_UP_FAILED",
  SIGN_OUT = "SIGN_OUT",
  SIGN_OUT_FAILED = "SIGN_OUT_FAILED",
  CREATE_USER = "CREATE_USER",
  CREATE_USER_FAILED = "CREATE_USER_FAILED",

  // General Actions
  AI_CHAT_REQUEST = "AI_CHAT_REQUEST",
  AI_CHAT_FAILED = "AI_CHAT_FAILED",
}

export default LogAction;
